### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by zachadamietz** [MartyMcKnife/BeatSaberSpotify#1]
[beatsaverspotify.log](https://github.com/MartyMcKnife/BeatSaberSpotify/files/4761212/beatsaverspotify.log)

**Comment by MartyMcKnife** [comment]
So for anyone getting the module import error, its because I was using some really funky code to try and install the stuff via the python script, and not telling you to. For now, open up CMD and type in

pip install requests

pip install spotipy

pip install fuzzywuzzy

pip install wget

I should be able to fix it later today, but that's just a short term fix for now

**Comment by MartyMcKnife** [comment]
Should be fixed now - let me know if you have any more problems :)
